### ISSUE TITLE
multiprocessing in python

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qr-core#29]
multiple QM jobs run as a batch, collect results and process, re-run batch.....repeat

**Comment by yangjackie** [comment]
This is one of the smallest snippet that introduces the basics:
http://eli.thegreenplace.net/2012/01/24/distributed-computing-in-python-with-multiprocessing

More elaborated things are basically along this sort of line. my code is very messy at the moment, so it might not be easy to work out what i did in it.

**Comment by mpwaller** [comment]
feel free to share your cleaned up version! :) 

the messy version you can keep hidden away...!

**Comment by mpwaller** [comment]
@yangjackie thanks for the link

**Comment by pafonine** [comment]
As I mentioned the other day, we use Python's multiprocessing frequently 
in cctbx. For example, see

mmtbx/refinement/real_space/explode_and_refine.py

lines #122-130.

This is done using easy_mp, which is a cctbx based convenience wrapper 
around standard Python tools.

There are at least three articles that describe details:

1) cctbx tools for transparent parallel job execution in Python. I. 
Foundations
2) cctbx tools for transparent parallel job execution in Python. II. 
Convenience functions for the impatient
3) cctbx tools for transparent parallel job execution in Python. III. 
Remote access

all located here:
https://www.phenix-online.org/newsletter/

Pavel

**Comment by pafonine** [comment]
P.S.: In case I wasn't clear enough: easy_mp is what we can use right 
now in qr as it comes standard from cctbx.
Pavel

**Comment by yangjackie** [comment]
For Mark and Min:

The code on entdecker repository now is basically a stripped-down and tidied up version of my server-client code. Few things that are supposed to be in but left out (due to complex dependencies on the data structure, scientific codes, etc, that basically is not a necessary part of the underlying server-client infrastructures) are:

1. Most of the data domain model.
2. Generating dimers from crystals, (so i just assume there's already a long list of dimers).
3. Restarting and continuation of a batch job. basically just some long data checking logics on client side.
4. All the codes that are needed to run ADF are admitted. Just a place holder there to point out at what point ADF was called, and everything need to be done on the server side for running the ADF will go there.

Have fun!

**Comment by mpwaller** [comment]
@zhengmin317  can this be closed now?
